name: Docker Build

on:
  schedule:
    - cron: "23 2 * * *"
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  NAME: "aeris1one/openldap"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Set VERSION
      id: version
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          VERSION="stable"
        elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          VERSION="dev"
        elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION="${{ github.ref }}" | sed -e 's/refs\/tags\/\(.*\)[-v]\(.*\)/\1\2/'
        else
          VERSION="${{ github.ref_name }}-dev"
        fi
        VERSION=$(echo "${VERSION}" | sed 's|/|-|g')
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./image
        push: true
        sbom: true
        provenance: mode=max
        platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/386
        tags: ${{ env.NAME }}:${{ steps.version.outputs.VERSION }}
        labels: |
          org.opencontainers.image.title=Light Baseimage
          org.opencontainers.image.description=Lightweight base image for Docker
          org.opencontainers.image.url=https://github.com/aeris1one/container-baseimage